version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U pytest pytest-cov --user
      - run: pip3 install .[all] --user
      # The actual test
      - run:
          command: pytest --cov perfplot
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build

